### ISSUE TITLE
Question about the torque and avaliable files.

### ISSUE THREAD

**Issue by quantingxie** [SwannSchilling/Cycloidal-Drive#2]
Hi, I love your design! It's really well-designed for printability! May I ask you some questions regarding this setup? 
1. Did you test the maximum torque/cm that can be output from this setup? 
2. Are the .step or .prt files available for us to change the gear ratio?

Thank you so much!

**Comment by SwannSchilling** [comment]
The Tarot 4108 has 380KV so the Torque Constant can be calculated over here 
https://www.fxsolver.com/solve/
So this BLDC should have a torque constant of 0.02513 Nm/A

I am using a 1:40 gearbox on top of that BLDC motor...
So with the gearbox working I will need to measure the amps the motor draws, but lets consider 2.5Amps...
0.029 * 2.5 = 0.0725Nm

By multiplying a gear ratio of 40, the idle torque on the output is 0.0725*40 = 2.9Nm

You can change the ratio by using this script
https://github.com/SwannSchilling/Cycloidal-Drive/blob/main/Cycloidal.py

You can see how it works in this example
https://www.youtube.com/watch?v=dtE1o2hR0Ec&t=17s

**Comment by quantingxie** [comment]
Hi, thank you for the detailed reply! 

I am not too sure if I figured out how it works, I printed the gear using your Python file, and the two rotor gears are too tight to fit on the ring gear. I have to sand it down a bit but they are still fit really tight on the ring gear and not turning. I used a resin printer so the accuracy should be really good. Is the ring gear not supposed to turn with respect to the rotor gears?

And we are not requiring those small bearings anymore with the new design right, will this cause a lot of heat due to friction? 

Thank you and looking forward to your reply!

**Comment by SwannSchilling** [comment]
Unfortunately a resin printer will not work for this, I tried it myself and it does not work at all.
The gears need to be very precise in size and due to the nature of resin it will change in size during the curing process and also there will be deformations during the printing process since the resin is very soft when being printed!

I was also dissapointed when I found out!
ABS or PET works best for these applications!

You can try without the bearings but I would not recommend it, you would also need to change the design accordingly!

**Comment by quantingxie** [comment]
Thank you so much!
